#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'

# Simple Regex
require 'regexp_ast.rb'


class RegexpSimple < Racc::Parser

module_eval(<<'...end regexp_nfa.y/module_eval...', 'regexp_nfa.y', 26)
  def parse(str)
    @q = []
    str = str.gsub(/(H|L){(\d+)}/) do
      $1 * $2.to_i
    end
    until str.empty?
      case str[0]
      when ' '
      when '|'
        @q.push ['|', '|']
      when /[A-Z]/
        @q.push [:ALPHABET, str[0]]
      when '*'
        @q.push ['*', '*']
      when '('
        @q.push ['(', '(']
      when ')'
        @q.push [')', ')']
      end
      str = str[1..-1]
    end
    @q.push [false, '$end']
    do_parse
  end

  def next_token
    @q.shift
  end

...end regexp_nfa.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     9,     8,     4,     6,     5,     9,     8,     4,    13,     5,
     8,     4,    11,     5,     8,     4,     4,     5,     5,     4,
     4,     5,     5 ]

racc_action_check = [
     2,     2,     2,     1,     2,    10,    10,    10,    10,    10,
    12,    12,     6,    12,     7,     7,     9,     7,     9,     4,
     0,     4,     0 ]

racc_action_pointer = [
    14,     3,    -4,   nil,    13,   nil,    12,     9,   nil,    10,
     1,   nil,     5,   nil ]

racc_action_default = [
    -2,    -9,    -1,    -6,    -9,    -8,    -9,    -5,    -3,    -9,
    -9,    14,    -4,    -7 ]

racc_goto_table = [
     2,     1,   nil,   nil,    10,   nil,   nil,   nil,   nil,    12 ]

racc_goto_check = [
     2,     1,   nil,   nil,     2,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,     0,   nil ]

racc_goto_default = [
   nil,   nil,     7,     3 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 10, :_reduce_none,
  0, 10, :_reduce_2,
  2, 11, :_reduce_3,
  3, 11, :_reduce_4,
  2, 11, :_reduce_5,
  1, 11, :_reduce_none,
  3, 12, :_reduce_7,
  1, 12, :_reduce_8 ]

racc_reduce_n = 9

racc_shift_n = 14

racc_token_table = {
  false => 0,
  :error => 1,
  :STAR => 2,
  :CONCAT => 3,
  "|" => 4,
  "*" => 5,
  "(" => 6,
  ")" => 7,
  :ALPHABET => 8 }

racc_nt_base = 9

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STAR",
  "CONCAT",
  "\"|\"",
  "\"*\"",
  "\"(\"",
  "\")\"",
  "ALPHABET",
  "$start",
  "target",
  "exp",
  "primary" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'regexp_nfa.y', 8)
  def _reduce_2(val, _values, result)
     result = 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'regexp_nfa.y', 10)
  def _reduce_3(val, _values, result)
     result = StarNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regexp_nfa.y', 11)
  def _reduce_4(val, _values, result)
     p val ;result = DisjunctionNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regexp_nfa.y', 12)
  def _reduce_5(val, _values, result)
     result = ConcatNode.new(val[0],val[1]) 
    result
  end
.,.,

# reduce 6 omitted

module_eval(<<'.,.,', 'regexp_nfa.y', 15)
  def _reduce_7(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regexp_nfa.y', 16)
  def _reduce_8(val, _values, result)
     result = ValueNode.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class RegexpSimple


